const potentialChickens = [
  { id: "U027CLUME", name: "gstamp", team: "mercury" },
  { id: "U02DERN4E", name: "khayman", team: "artemis" },
  { id: "U0274DF37", name: "asellitt", team: "artemis" },
  { id: "UU4E73JCD", name: "Heidi.k", team: "discover" },
  { id: "U07271PS5", name: "prasanna", team: "discover" },
  { id: "U0G1LM222", name: "stacey", team: "attract" },
  { id: "U1SG7A284", name: "bakes", team: "mercury" },
  { id: "UDWHM1JTZ", name: "riana.ferreira", team: "artemis" },
  { id: "U02PS4KKA", name: "bordo", team: "discover" },
  { id: "U5G7D3MK7", name: "grant.tibbey", team: "gemini" },
  { id: "UDWR5TJLR", name: "ali.graham", team: "gemini" },
  { id: "UEAR25K88", name: "amanda.varella", team: "artemis" },
  { id: "UF72FC073", name: "Viv", team: "discover" },
  { id: "U025K202K", name: "notahat", team: "mercury" },
  { id: "U639C9S0H", name: "oliver.diestel", team: "attract" },
  { id: "UDJU1AL0K", name: "zoltan.toth", team: "attract" },
  { id: "U8G3NFUMD", name: "emily.koop", team: "attract" },
  { id: "U0F58P3DJ", name: "fraserxu", team: "discover" },
  { id: "U0286USDZ", name: "riley", team: "experience" },
  { id: "U0K8Z1KD1", name: "kelle", team: "experience" },
  { id: "UFM0UL2GG", name: "claire.grooby", team: "experience" },
  { id: "U02BLQE2B", name: "matter", team: "experience" },
  { id: "UGWEUTNH5", name: "Izzy", team: "experience" },
  { id: "U15HUNCRJ", name: "Sam McKenna (Tue-Fri)", team: "experience" },
  { id: "U027QM5S1", name: "madlep", team: "discover" },
  { id: "U1D5E8R6K", name: "pawel.galazka", team: "attract" },
  { id: "UEAUU2F6D", name: "lucascaton", team: "attract" },
  { id: "U01PNQK0XGX", name: "raf", team: "attract" },
  { id: "U01S1TCQUAU", name: "Dan C", team: "discover" },
]

module.exports = potentialChickens
